/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: p1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "p1.pb-c.h"
void   trans__one__init
                     (Trans__One         *message)
{
  static const Trans__One init_value = TRANS__ONE__INIT;
  *message = init_value;
}
size_t trans__one__get_packed_size
                     (const Trans__One *message)
{
  assert(message->base.descriptor == &trans__one__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trans__one__pack
                     (const Trans__One *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trans__one__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trans__one__pack_to_buffer
                     (const Trans__One *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trans__one__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Trans__One *
       trans__one__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Trans__One *)
     protobuf_c_message_unpack (&trans__one__descriptor,
                                allocator, len, data);
}
void   trans__one__free_unpacked
                     (Trans__One *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trans__one__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor trans__one__field_descriptors[3] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trans__One, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trans__One, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Trans__One, c),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trans__one__field_indices_by_name[] = {
  0,   /* field[0] = a */
  1,   /* field[1] = b */
  2,   /* field[2] = c */
};
static const ProtobufCIntRange trans__one__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor trans__one__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trans.One",
  "One",
  "Trans__One",
  "trans",
  sizeof(Trans__One),
  3,
  trans__one__field_descriptors,
  trans__one__field_indices_by_name,
  1,  trans__one__number_ranges,
  (ProtobufCMessageInit) trans__one__init,
  NULL,NULL,NULL    /* reserved[123] */
};
